### ISSUE TITLE
Remove Install Argo page (intro_argo_quick_start.md )

### ISSUE THREAD

**Issue by cyee88** [argoproj/docs#1]
The https://argoproj.github.io/argo-site/#/get-started/installation page has all the installation information...so there's no need to have the https://argoproj.github.io/argo-site/#/docs;doc=quickstart%2Fintro_argo_quick_start.md page. 

Related issue: https://github.com/argoproj/argo-site/issues/10

**Comment by alexmt** [comment]
Docs had been updated
